// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexd_QvqBFOWuVsABKgmliTncFrcYOgc4',
    appId: '1:345311574655:android:f5b0d1233b9233c3e11d4a',
    messagingSenderId: '345311574655',
    projectId: 'test-6e657',
    storageBucket: 'test-6e657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYu1VmjhraHMFhELhZhu_8pY-RV2vzXE',
    appId: '1:345311574655:ios:5e63a12ad360b574e11d4a',
    messagingSenderId: '345311574655',
    projectId: 'test-6e657',
    storageBucket: 'test-6e657.firebasestorage.app',
    iosBundleId: 'com.example.aiInspection',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXVDU57bl81YEk4BAvdK3c9BiBYlKrhA',
    appId: '1:345311574655:web:1f9a4a67596936fce11d4a',
    messagingSenderId: '345311574655',
    projectId: 'test-6e657',
    authDomain: 'test-6e657.firebaseapp.com',
    storageBucket: 'test-6e657.firebasestorage.app',
    measurementId: 'G-0BLP83KDNE',
  );

}